let data;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
async function api(url,options={}){const r=await fetch(url,options);if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Erro na operação');return r.json();}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function serviceIcon(s){return s.iconImage?`<img class="admin-icon-preview" src="${esc(s.iconImage)}" alt="">`:`<i class="bi ${esc(s.iconClass||'bi-briefcase')}"></i>`;}
const iconOptions=['bi-link-45deg','bi-globe2','bi-instagram','bi-facebook','bi-linkedin','bi-youtube','bi-tiktok','bi-twitter-x','bi-whatsapp','bi-telegram','bi-pinterest','bi-github','bi-behance','bi-dribbble','bi-briefcase','bi-images','bi-file-earmark-person','bi-envelope','bi-telephone','bi-geo-alt'];
const socialPlatforms={Instagram:'bi-instagram',Facebook:'bi-facebook',LinkedIn:'bi-linkedin',YouTube:'bi-youtube',TikTok:'bi-tiktok',X:'bi-twitter-x',WhatsApp:'bi-whatsapp',Telegram:'bi-telegram',Pinterest:'bi-pinterest',GitHub:'bi-github',Behance:'bi-behance',Dribbble:'bi-dribbble',Website:'bi-globe2'};
async function init(){try{const s=await api('/api/admin/session');if(!s.authenticated)return location.replace('/admin/');data=await api('/api/site');renderAll();}catch(e){console.error(e);location.replace('/admin/');}}
$('#logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'}).catch(()=>{});location.replace('/admin/');};
$$('#adminNav button').forEach(btn=>btn.onclick=()=>{$$('#adminNav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.tab').forEach(t=>t.classList.remove('active'));$(`#tab-${btn.dataset.tab}`).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});});
function renderAll(){renderSettings();renderServices();renderPortfolio();renderTeam();renderPartners();renderLinks();renderSocials();renderSecurity();}
function renderSettings(){const s=data.settings||{};$('#settingsAdmin').innerHTML=`
<form class="panel form-grid" id="settingsForm">
<label>Nome do site<input name="siteName" value="${esc(s.siteName||'Yuran Multicerviços')}"></label><label>Slogan<input name="tagline" value="${esc(s.tagline||'')}"></label>
<label class="span-2">Título principal<input name="heroTitle" value="${esc(s.heroTitle||'')}"></label><label class="span-2">Texto principal<textarea name="heroText" rows="3">${esc(s.heroText||'')}</textarea></label>
<label>WhatsApp<input name="whatsapp" value="${esc(s.whatsapp||'')}"></label><label>Telefone<input name="phone" value="${esc(s.phone||'')}"></label>
<label>E-mail<input name="email" value="${esc(s.email||'')}"></label><label>Localização<input name="location" value="${esc(s.location||'')}"></label>
<label>Cor principal do site<input name="primaryColor" type="color" value="${esc(s.primaryColor||'#151a16')}"></label><label>Cor da área principal (hero)<input name="heroColor" type="color" value="${esc(s.heroColor||'#00C9A7')}"></label><label>Cor hover do menu<input name="navHoverColor" type="color" value="${esc(s.navHoverColor||'#00C9A7')}"></label>
<label class="span-2">Sobre nós<textarea rows="7" name="about">${esc(s.about||'')}</textarea></label><button class="span-2">Guardar informações e cores</button></form>
<form class="panel upload-form asset-form" id="assetsForm"><div><b>Logotipo do site</b><small class="help">O mesmo logotipo aparece no cabeçalho e em destaque na área principal.</small>${s.logo?`<img class="asset-preview" src="${esc(s.logo)}">`:''}<input type="file" name="logo" accept="image/*"></div><div><b>Favicon / ícone do navegador</b>${s.favicon?`<img class="favicon-preview" src="${esc(s.favicon)}">`:''}<input type="file" name="favicon" accept="image/*"></div><button class="full">Guardar identidade visual</button></form>`;
$('#settingsForm').onsubmit=async e=>{e.preventDefault();try{data.settings=await api('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});alert('Informações guardadas.');}catch(err){alert(err.message)}};
$('#assetsForm').onsubmit=async e=>{e.preventDefault();try{data.settings=await api('/api/admin/settings/assets',{method:'POST',body:new FormData(e.currentTarget)});renderSettings();alert('Identidade visual guardada.');}catch(err){alert(err.message)}};}
function renderServices(){const icons=['bi-lightning-charge','bi-palette','bi-megaphone','bi-flower1','bi-heart-pulse','bi-tools','bi-laptop','bi-buildings','bi-camera','bi-briefcase'];$('#servicesAdmin').innerHTML=`<form class="panel upload-form" id="serviceForm" enctype="multipart/form-data"><input name="title" placeholder="Nome do serviço" required><select name="iconClass">${icons.map(i=>`<option value="${i}">${i}</option>`).join('')}</select><label>Cor do serviço<input name="color" type="color" value="#00C9A7"></label><label>Ícone personalizado (opcional)<input type="file" name="iconImage" accept="image/*"></label><label class="full">Banner da página do serviço<input type="file" name="banner" accept="image/*"></label><input class="full" name="description" placeholder="Descrição curta para o cartão" required><textarea class="full" name="details" rows="6" placeholder="Descrição completa da página do serviço"></textarea><button class="full">Adicionar serviço</button></form><div class="admin-grid">${data.services.map(s=>`<article class="admin-card"><div class="service-admin-head" style="--service-color:${esc(s.color||'#00C9A7')}"><span class="service-admin-icon">${serviceIcon(s)}</span><h3>${esc(s.title)}</h3></div>${s.banner?`<img src="${esc(s.banner)}" alt="">`:''}<p>${esc(s.description||'')}</p><details><summary>Editar serviço</summary><form class="stack edit-service-form" data-id="${esc(s.id)}"><input name="title" value="${esc(s.title)}" required><input name="iconClass" value="${esc(s.iconClass||'bi-briefcase')}" placeholder="Bootstrap icon: bi-palette"><label>Cor<input name="color" type="color" value="${esc(s.color||'#00C9A7')}"></label><textarea name="description" rows="3">${esc(s.description||'')}</textarea><textarea name="details" rows="6">${esc(s.details||s.description||'')}</textarea><label>Novo ícone personalizado<input type="file" name="iconImage" accept="image/*"></label><label>Novo banner<input type="file" name="banner" accept="image/*"></label><button>Guardar alterações</button></form></details><div class="actions"><a class="admin-link" target="_blank" href="/servico/${encodeURIComponent(s.id)}">Ver página ↗</a><button class="danger" onclick="removeItem('services','${s.id}')">Remover</button></div></article>`).join('')}</div>`;$('#serviceForm').onsubmit=async e=>{e.preventDefault();try{const item=await api('/api/admin/services',{method:'POST',body:new FormData(e.currentTarget)});data.services.push(item);renderServices();renderPortfolio();}catch(err){alert(err.message)}};$$('.edit-service-form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();try{const updated=await api(`/api/admin/services/${f.dataset.id}`,{method:'PUT',body:new FormData(f)});const i=data.services.findIndex(x=>x.id===f.dataset.id);data.services[i]=updated;renderServices();renderPortfolio();alert('Serviço atualizado.');}catch(err){alert(err.message)}});}
function renderPortfolio(){const options=data.services.map(s=>`<option value="${esc(s.title)}">${esc(s.title)}</option>`).join('');$('#portfolioAdmin').innerHTML=`<form class="panel upload-form" id="portfolioForm" enctype="multipart/form-data"><input name="title" placeholder="Título do projeto" required><select name="service" required><option value="">Serviço</option>${options}</select><label class="full">Imagens do projeto (pode selecionar várias)<input type="file" name="images" accept="image/*" multiple required></label><textarea class="full" name="description" rows="6" placeholder="Descrição completa"></textarea><input class="full" name="link" placeholder="Link externo (opcional)"><button class="full">Publicar trabalho</button></form><div class="admin-grid">${data.portfolio.map(p=>{const imgs=p.images?.length?p.images:(p.image?[p.image]:[]);return`<article class="admin-card">${imgs[0]?`<img src="${esc(imgs[0])}">`:''}<small>${esc(p.service||'')}</small><h3>${esc(p.title)}</h3><p>${esc(p.description||'')}</p><div class="mini">${imgs.length} imagem(ns)</div><button class="danger" onclick="removePortfolio('${p.id}')">Remover</button></article>`}).join('')}</div>`;$('#portfolioForm').onsubmit=async e=>{e.preventDefault();try{const item=await api('/api/admin/portfolio',{method:'POST',body:new FormData(e.currentTarget)});data.portfolio.unshift(item);renderPortfolio();}catch(err){alert(err.message)}};}
function renderTeam(){$('#teamAdmin').innerHTML=`<form class="panel upload-form" id="teamForm"><input name="name" placeholder="Nome" required><input name="role" placeholder="Função / especialidade" required><label class="full">Foto<input type="file" name="photo" accept="image/*"></label><textarea class="full" name="bio" placeholder="Breve biografia"></textarea><button class="full">Adicionar profissional</button></form><div class="admin-grid">${data.team.map(m=>`<article class="admin-card">${m.photo?`<img src="${esc(m.photo)}">`:''}<h3>${esc(m.name)}</h3><small>${esc(m.role)}</small><p>${esc(m.bio||'')}</p><form class="team-cv" onsubmit="uploadCv(event,'${m.id}')"><input type="file" name="cv" accept="application/pdf" required><button>${m.cv?'Trocar CV':'Adicionar CV'}</button></form>${m.cv?`<a class="mini" href="${esc(m.cv)}" target="_blank">Abrir CV ↗</a>`:''}<div class="actions"><button class="danger" onclick="removeItem('team','${m.id}')">Remover</button></div></article>`).join('')}</div>`;$('#teamForm').onsubmit=async e=>{e.preventDefault();try{const item=await api('/api/admin/team',{method:'POST',body:new FormData(e.currentTarget)});data.team.push(item);renderTeam();}catch(err){alert(err.message)}};}
window.uploadCv=async(e,id)=>{e.preventDefault();try{const u=await api(`/api/admin/team/${id}/cv`,{method:'POST',body:new FormData(e.currentTarget)});data.team[data.team.findIndex(x=>x.id===id)]=u;renderTeam();}catch(err){alert(err.message)}};
window.removePortfolio=async id=>{if(!confirm('Remover este projeto e todas as suas imagens?'))return;try{await api(`/api/admin/portfolio/${id}`,{method:'DELETE'});data.portfolio=data.portfolio.filter(x=>x.id!==id);renderPortfolio();}catch(err){alert(err.message)}};
window.removeItem=async(c,id)=>{if(!confirm('Remover este item?'))return;try{await api(`/api/admin/${c}/${id}`,{method:'DELETE'});data[c]=data[c].filter(x=>x.id!==id);renderAll();}catch(err){alert(err.message)}};
function renderPartners(){$('#partnersAdmin').innerHTML=`<form class="panel upload-form" id="partnerForm" enctype="multipart/form-data"><input name="name" placeholder="Nome do parceiro" required><label>Logotipo<input type="file" name="logo" accept="image/*"></label><input class="full" name="url" placeholder="www.exemplo.com ou https://exemplo.com"><button class="full">Adicionar parceiro</button></form><div class="admin-grid">${data.partners.map(p=>`<article class="admin-card">${p.logo?`<img class="partner-admin-logo" src="${esc(p.logo)}">`:''}<h3>${esc(p.name)}</h3><p>${esc(p.url||'')}</p><button class="danger" onclick="removeItem('partners','${p.id}')">Remover</button></article>`).join('')}</div>`;$('#partnerForm').onsubmit=async e=>{e.preventDefault();try{const item=await api('/api/admin/partners',{method:'POST',body:new FormData(e.currentTarget)});data.partners.push(item);renderPartners();}catch(err){alert(err.message)}};}
function renderLinks(){$('#linksAdmin').innerHTML=`<form class="panel upload-form" id="linkForm"><input name="title" placeholder="Título" required><input name="url" placeholder="https://..." required><label class="full">Ícone<select name="iconClass">${iconOptions.map(i=>`<option value="${i}">${i}</option>`).join('')}</select></label><button class="full">Adicionar ligação</button></form><div class="admin-grid">${data.links.map(l=>`<article class="admin-card"><h3><i class="bi ${esc(l.iconClass||'bi-link-45deg')}"></i> ${esc(l.title)}</h3><p>${esc(l.url)}</p><button class="danger" onclick="removeItem('links','${l.id}')">Remover</button></article>`).join('')}</div>`;$('#linkForm').onsubmit=async e=>{e.preventDefault();try{const item=await api('/api/admin/links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});data.links.push(item);renderLinks();}catch(err){alert(err.message)}};}
function renderSocials(){data.socials||=[];$('#socialsAdmin').innerHTML=`<form class="panel upload-form" id="socialForm"><label>Plataforma<select name="platform" id="socialPlatform">${Object.keys(socialPlatforms).map(n=>`<option value="${n}">${n}</option>`).join('')}</select></label><input name="url" placeholder="https://..." required><input type="hidden" name="iconClass" id="socialIconClass" value="bi-instagram"><button class="full">Adicionar rede social</button></form><div class="admin-grid social-admin-grid">${data.socials.map(x=>`<article class="admin-card social-admin-card"><div class="social-preview"><i class="bi ${esc(x.iconClass||socialPlatforms[x.platform]||'bi-link-45deg')}"></i></div><h3>${esc(x.platform||'Rede social')}</h3><p>${esc(x.url||'')}</p><button class="danger" onclick="removeItem('socials','${x.id}')">Remover</button></article>`).join('')}</div>`;const sel=$('#socialPlatform'),hidden=$('#socialIconClass');sel.onchange=()=>hidden.value=socialPlatforms[sel.value]||'bi-link-45deg';$('#socialForm').onsubmit=async e=>{e.preventDefault();try{const item=await api('/api/admin/socials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});data.socials.push(item);renderSocials();}catch(err){alert(err.message)}};}
function renderSecurity(){$('#securityAdmin').innerHTML=`<form class="panel security-form" id="passwordForm"><h3>Alterar senha do painel</h3><p class="help">A nova senha substitui a senha inicial configurada no Render e fica guardada de forma criptográfica.</p><input type="password" name="currentPassword" placeholder="Senha atual" required><input type="password" name="newPassword" minlength="8" placeholder="Nova senha (mín. 8 caracteres)" required><input type="password" name="confirmPassword" minlength="8" placeholder="Confirmar nova senha" required><button>Alterar senha</button></form><div class="panel recovery-info"><h3><i class="bi bi-key"></i> Recuperação em caso de esquecimento</h3><p>Para poder recuperar o acesso, crie no Render a variável de ambiente <code>ADMIN_RECOVERY_KEY</code> com uma chave longa e secreta. Depois, na tela de login, use <b>Esqueci a senha</b>.</p><p class="help">Não coloque essa chave no GitHub. Guarde-a fora do site, por exemplo num gestor de senhas.</p></div>`;$('#passwordForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));if(v.newPassword!==v.confirmPassword)return alert('As duas novas senhas não coincidem.');try{await api('/api/admin/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:v.currentPassword,newPassword:v.newPassword})});e.currentTarget.reset();alert('Senha alterada com sucesso.');}catch(err){alert(err.message)}};}
init();
